query get_current_user_query($id: uuid!) {
  authors_by_pk(id: $id) {
    id
    beeer_name
    email
    is_deleted
    is_suspended
    is_verified
    profile_detail {
      id
      first_name
      last_name
      location
      phone_number
      profession
      profile_picture
      website
      work_email
      work_place
      date_of_birth
      bio
      author_id
      created_at
      updated_at
    }
    social_links {
      id
      link
      enum {
        name
        icon
      }
      created_at
      updated_at
    }
    certificates_aggregate {
      aggregate {
        count
      }
    }
    educations_aggregate {
      aggregate {
        count
      }
    }
    projects_aggregate {
      aggregate {
        count
      }
    }
    blogs_aggregate {
      aggregate {
        count
      }
    }
  }
}

query get_certificates_query($author_id: uuid!) {
  certificates(where: { author_id: { _eq: $author_id } }) {
    id
    author_id
    title
    description
    location
    start_date
    end_date
    image
    created_at
    updated_at
  }
}

query get_projects_query($author_id: uuid!) {
  projects(where: { author_id: { _eq: $author_id } }) {
    skills
    end_date
    start_date
    client
    description
    image
    link
    location
    subtitle
    title
    created_at
    updated_at
    author_id
    id
  }
}

query get_educations_query($author_id: uuid!) {
  educations(where: { author_id: { _eq: $author_id } }) {
    id
    image
    author_id
    title
    school
    location
    start_date
    end_date
    created_at
    updated_at
  }
}

query GetAuthors_query {
  authors {
    is_deleted
    is_suspended
    is_verified
    beeer_name
    code
    email
    created_at
    updated_at
    id
    profile_detail {
      first_name
      last_name
      phone_number
      location
      profession
      profile_picture
      website
      work_email
      work_place
      date_of_birth
      bio
      id
    }
    certificates_aggregate {
      aggregate {
        count
      }
    }
    educations_aggregate {
      aggregate {
        count
      }
    }
    projects_aggregate {
      aggregate {
        count
      }
    }
    blogs_aggregate {
      aggregate {
        count
      }
    }
  }
}

query get_single_user_query($id: uuid!) {
  authors(where: { id: { _eq: $id } }) {
    is_deleted
    is_suspended
    is_verified
    beeer_name
    code
    email
    created_at
    updated_at
    id
    profile_detail {
      first_name
      last_name
      phone_number
      location
      profession
      profile_picture
      website
      work_email
      work_place
      date_of_birth
      bio
      id
    }
    blogs {
      id
      image
      title
      subtitle
      tags
      description
      created_at
      updated_at
    }
    projects {
      id
      image
      link
      location
      description
      client
      title
      subtitle
      start_date
      end_date
      skills
      created_at
      updated_at
    }
    educations {
      id
      image
      title
      school
      location
      start_date
      end_date
      created_at
      updated_at
    }
    certificates {
      id
      title
      location
      description
      image
      start_date
      end_date
      created_at
      updated_at
    }
    social_links {
      id
      link
      enum {
        icon
        name
      }
    }
  }
}
