query get_current_user_query($id: uuid!) {
  authors_by_pk(id: $id) {
    id
    beeer_name
    email
    is_deleted
    is_suspended
    is_verified
    profile_detail {
      id
      first_name
      last_name
      location
      phone_number
      profession
      profile_picture
      website
      work_email
      work_place
      date_of_birth
      bio
      author_id
      created_at
      updated_at
    }
    social_links {
      id
      link
      enum {
        name
        icon
      }
      created_at
      updated_at
    }
  }
}
