mutation update_profile_detail(
  $id: uuid!
  $first_name: String!
  $last_name: String!
  $bio: String!
  $date_of_birth: date!
  $location: String!
  $phone_number: String!
  $profession: String!
  $website: String!
  $work_email: String!
  $work_place: String!
) {
  update_profile_details_by_pk(
    pk_columns: { id: $id }
    _set: {
      bio: $bio
      date_of_birth: $date_of_birth
      first_name: $first_name
      last_name: $last_name
      location: $location
      phone_number: $phone_number
      profession: $profession
      website: $website
      work_email: $work_email
      work_place: $work_place
    }
  ) {
    id
  }
}

mutation update_social_links_query(
  $id: uuid!
  $name: social_medias_enum_enum!
  $link: String!
) {
  update_social_links_by_pk(
    pk_columns: { id: $id }
    _set: { name: $name, link: $link }
  ) {
    id
  }
}

mutation update_certificates_query(
  $id: uuid!
  $end_date: date!
  $start_date: date!
  $description: String!
  $image: String!
  $location: String!
  $title: String
) {
  update_certificates_by_pk(
    pk_columns: { id: $id }
    _set: {
      end_date: $end_date
      start_date: $start_date
      description: $description
      image: $image
      location: $location
      title: $title
    }
  ) {
    id
  }
}

mutation update_project_query(
  $id: uuid!
  $image: String!
  $title: String!
  $subtitle: String!
  $description: String!
  $start_date: date!
  $end_date: date!
  $location: String
  $client: String
  $link: String
  $skills: [String!]
) {
  update_projects_by_pk(
    pk_columns: { id: $id }
    _set: {
      image: $image
      title: $title
      subtitle: $subtitle
      description: $description
      start_date: $start_date
      end_date: $end_date
      location: $location
      client: $client
      link: $link
      skills: $skills
    }
  ) {
    id
  }
}

mutation update_education_query(
  $id: uuid!
  $end_date: date!
  $start_date: date!
  $location: String!
  $school: String!
  $title: String!
  $image: String!
) {
  insert_educations_one(
    pk_columns: { id: $id }
    _set: {
      end_date: $end_date
      start_date: $start_date
      location: $location
      school: $school
      title: $title
      image: $image
    }
  ) {
    id
  }
}
