mutation InsertComments(
  $comment: String!
  $blog_id: uuid!
  $commentor_id: uuid!
) {
  insert_comments_one(
    object: {
      comment: $comment
      blog_id: $blog_id
      commentor_id: $commentor_id
    }
  ) {
    id
  }
}

mutation update_comment_query($id: uuid!, $comment: String!) {
  update_comments_by_pk(_set: { comment: $comment }, pk_columns: { id: $id }) {
    id
  }
}
