query get__my_blogs_query($author_id: uuid!) {
  blogs(where: { author_id: { _eq: $author_id } }) {
    id
    author_id
    title
    subtitle
    description
    image
    category
    created_at
    updated_at
    tags
  }
}

query get_single_blog_query($author_id: uuid!, $id: uuid!) {
  blogs(
    where: { _and: [{ author_id: { _eq: $author_id }, id: { _eq: $id } }] }
  ) {
    id
    author_id
    title
    subtitle
    description
    image
    category
    created_at
    updated_at
    tags
  }
}

query get_feeds_query {
  blogs(order_by: { updated_at: desc }) {
    tags
    category
    description
    image
    subtitle
    title
    created_at
    updated_at
    author_id
    id
    author {
      email
      beeer_name
      profile_detail {
        profile_picture
      }
    }
  }

  authors(where: { profile_detail: { first_name: { _is_null: false } } }) {
    is_deleted
    is_suspended
    is_verified
    beeer_name
    code
    email
    created_at
    updated_at
    id
    profile_detail {
      first_name
      last_name
      phone_number
      location
      profession
      profile_picture
      website
      work_email
      work_place
      date_of_birth
      bio
      id
    }
    certificates_aggregate {
      aggregate {
        count
      }
    }
    educations_aggregate {
      aggregate {
        count
      }
    }
    projects_aggregate {
      aggregate {
        count
      }
    }
    blogs_aggregate {
      aggregate {
        count
      }
    }
  }
}

query GetSingleBlogs($id: uuid!) {
  blogs(where: { id: { _eq: $id } }) {
    tags
    category
    description
    image
    subtitle
    title
    created_at
    updated_at
    author_id
    id
    author {
      email
      beeer_name
      profile_detail {
        first_name
        last_name
        phone_number
        website
        profile_picture
      }
      social_links {
        id
        link
        enum {
          icon
          name
        }
      }
    }
    likes_aggregate {
      aggregate {
        count
      }
    }
    likes {
      liker {
        id
      }
    }
    comments(order_by: { updated_at: desc }) {
      id
      comment
      created_at
      updated_at
      blog_id
      author {
        id
        beeer_name
        profile_detail {
          profile_picture
          first_name
          last_name
        }
      }
      replies(order_by: { updated_at: desc }) {
        id
        reply
        created_at
        updated_at
        author {
          id
          beeer_name
          profile_detail {
            first_name
            last_name
            profile_picture
          }
        }
      }
      replies_aggregate {
        aggregate {
          count
        }
      }
    }
  }
}
