-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE projects
-- ADD CONSTRAINT author_unique_projects_constraint UNIQUE (author_id, title);
